### ISSUE TITLE
Broken links for all the images on the "Look up an issue" page

### ISSUE THREAD

**Issue by jypeter** [ES-DOC/esdoc-errata-client#18]
@AtefBN I'm visiting the [Look up an issue](https://es-doc.github.io/esdoc-errata-client/searchUI.html) and the images/logos do not show. Seemingly because all the links to the images are broken

I think that's just because you renamed the _images_ directory to `_images` (https://github.com/ES-DOC/esdoc-errata-client/commit/75943e6970cf2ea6cbd57ff5e86cc3bb51296ca1) , so it should be easy to fix. This probably also means that there are broken links on other pages!

**Comment by AtefBN** [comment]
hi @jypeter I see that issue indeed. I think Github Pages chooses to disregard the files under directories starting with an underscore including _images in this instance. 
I'll recompile the pages and reupload asap.

**Comment by jypeter** [comment]
I have just found this old issue. I can see the missing images reported in the initial issue, so I'm closing the issue
