### ISSUE TITLE
"AUTHORIZATION FAILED" error not specific enought

### ISSUE THREAD

**Issue by glevava** [ES-DOC/esdoc-errata-client#2]
When the GitHub user is not part of the appropriate ES-DOC-INSTITUTIONAL team, precise the "AUTHORIZATION FAILED" error. Something like "Your are not allowed to publish errata on behalf of XXX. Please contact....etc" could be clearer.

**Comment by AtefBN** [comment]
Version 2.6 of the client adds a more detailed description of the error, especially for authentication and authorization errors.
